site_name: Zest
pages:
    - Home: index.md
    - Installation: installation.md
    - Configuration: configuration.md
    - Routing: routing.md
    - Controllers: controller.md
    - Views: views.md
    - Integrating twig with Zest: integrating-twig-with-Zest.md
    - Models: model.md
    - Validation: validation.md
    - Sending Mail: mail.md
    - Database Manipulation: database.md
    - Session Handling: session.md
    - Cryptography: cryptography.md
    - Site Maintenance: maintenance.md
    - Zest Console: console.md
    - Components: component.md
    - Upgrade From 2.0.1: UPGRADE-2.0.2.md
    - Upgrade From 1.9.4: UPGRADE-2.0.1.md
    - Old Upgrades: Old-Upgrade.md
    - Contribute: zestcontribute.md
theme: readthedocs    
    

